# Use the official Node.js image from the Docker Hub
FROM node:20

RUN apt-get update && apt-get install -y libvips-dev && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install -g

RUN npm install sharp --platform=linux

#RUN npm install pm2 -g

# Copy the rest of your application code
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Command to run your application
CMD ["node", "server.js"] 
